import { item, type ScriptSuggestion } from "./scriptAutocompleteHelpers";

export const ROOT_SUGGESTIONS: ScriptSuggestion[] = [
  item("pm", "pm", "variable", "Postman sandbox API", "Postman"),
  item("console", "console", "variable", "Console logging API", "Console"),
  item("crypto", "crypto", "variable", "Web Crypto API", "Crypto"),
  item(
    "fetch",
    "fetch()",
    "function",
    "Fetch HTTP resource",
    "(input, init?) => Promise<Response>",
  ),
  item("JSON", "JSON", "class", "JSON parse/stringify helpers", "JSON"),
  item("Math", "Math", "class", "Math constants and functions", "Math"),
  item("Date", "Date", "class", "Date constructor", "DateConstructor"),
  item("Object", "Object", "class", "Object constructor", "ObjectConstructor"),
  item("Array", "Array", "class", "Array constructor", "ArrayConstructor"),
  item("String", "String", "class", "String constructor", "StringConstructor"),
  item("Number", "Number", "class", "Number constructor", "NumberConstructor"),
  item(
    "Boolean",
    "Boolean",
    "class",
    "Boolean constructor",
    "BooleanConstructor",
  ),
  item(
    "parseInt",
    "parseInt(value, 10)",
    "function",
    "Parse string to integer",
    "(string, radix?) => number",
  ),
  item(
    "parseFloat",
    "parseFloat(value)",
    "function",
    "Parse string to number",
    "(string) => number",
  ),
  item(
    "setTimeout",
    "setTimeout(function () {\n    \n}, 0)",
    "function",
    "Run callback after delay",
    "(handler, timeout) => number",
  ),
  item(
    "clearTimeout",
    "clearTimeout(id)",
    "function",
    "Clear timeout",
    "(id) => void",
  ),
  item(
    "encodeURIComponent",
    "encodeURIComponent(value)",
    "function",
    "Encode URL component",
    "(value) => string",
  ),
  item(
    "decodeURIComponent",
    "decodeURIComponent(value)",
    "function",
    "Decode URL component",
    "(value) => string",
  ),
];
