import {
  headerSuggestions,
  item,
  type ScriptSuggestion,
  variableStoreSuggestions,
} from "./scriptAutocompleteHelpers";

export const POSTMAN_MEMBERS: Record<string, ScriptSuggestion[]> = {
  pm: [
    item(
      "collectionVariables",
      "collectionVariables",
      "property",
      "Collection variables",
      "PostmanVariableScope",
    ),
    item("cookies", "cookies", "property", "Cookie helpers", "PostmanCookies"),
    item(
      "datasets",
      "datasets",
      "property",
      "Dataset helpers",
      "PostmanDatasets",
    ),
    item(
      "environment",
      "environment",
      "property",
      "Environment variables",
      "PostmanVariableScope",
    ),
    item(
      "execution",
      "execution",
      "property",
      "Execution metadata",
      "PostmanExecution",
    ),
    item(
      "expect",
      "expect(value)",
      "function",
      "Assertion helper",
      "Chai.expect",
    ),
    item(
      "globals",
      "globals",
      "property",
      "Global variables",
      "PostmanVariableScope",
    ),
    item(
      "info",
      "info",
      "property",
      "Request and script metadata",
      "PostmanInfo",
    ),
    item(
      "iterationData",
      "iterationData",
      "property",
      "Iteration data variables",
      "PostmanVariableScope",
    ),
    item(
      "message",
      "message",
      "property",
      "Current execution message",
      "PostmanMessage",
    ),
    item("request", "request", "property", "Current request", "PostmanRequest"),
    item(
      "require",
      'require("module")',
      "function",
      "Load sandbox package",
      "(module) => any",
    ),
    item(
      "response",
      "response",
      "property",
      "Current response",
      "PostmanResponse",
    ),
    item(
      "sendRequest",
      'sendRequest("https://example.com", function (err, response) {\n    \n})',
      "function",
      "Send HTTP request",
      "(request, callback?) => Promise<Response>",
    ),
    item(
      "test",
      'test("name", function () {\n    \n})',
      "function",
      "Create a test",
      "(name, fn) => void",
    ),
    item("vault", "vault", "property", "Vault secrets", "PostmanVault"),
    item(
      "variables",
      "variables",
      "property",
      "Scoped variables",
      "PostmanVariableScope",
    ),
    item(
      "visualizer",
      "visualizer",
      "property",
      "Response visualizer",
      "PostmanVisualizer",
    ),
  ],
  "pm.environment": variableStoreSuggestions("Environment variable store"),
  "pm.collectionVariables": variableStoreSuggestions(
    "Collection variable store",
  ),
  "pm.globals": variableStoreSuggestions("Global variable store"),
  "pm.variables": variableStoreSuggestions("Scoped variable store"),
  "pm.iterationData": variableStoreSuggestions("Iteration data store"),
  "pm.cookies": [
    item(
      "get",
      'get("name")',
      "method",
      "Get cookie",
      "(name) => string | undefined",
    ),
    item(
      "has",
      'has("name")',
      "method",
      "Check cookie exists",
      "(name) => boolean",
    ),
    item(
      "toObject",
      "toObject()",
      "method",
      "Convert cookies to object",
      "() => object",
    ),
    item("jar", "jar()", "method", "Get cookie jar", "() => CookieJar"),
  ],
  "pm.info": [
    item("eventName", "eventName", "property", "Script event name", "string"),
    item("iteration", "iteration", "property", "Current iteration", "number"),
    item("requestId", "requestId", "property", "Request id", "string"),
    item("requestName", "requestName", "property", "Request name", "string"),
    item("collectionId", "collectionId", "property", "Collection id", "string"),
  ],
  "pm.execution": [
    item("location", "location", "property", "Execution location", "object"),
    item(
      "skipRequest",
      "skipRequest()",
      "method",
      "Skip current request",
      "() => void",
    ),
    item(
      "setNextRequest",
      "setNextRequest(null)",
      "method",
      "Set next request",
      "(name | null) => void",
    ),
  ],
  "pm.response": [
    item(
      "json",
      "json()",
      "method",
      "Parse response body as JSON",
      "() => any",
    ),
    item(
      "text",
      "text()",
      "method",
      "Read response body as text",
      "() => string",
    ),
    item("code", "code", "property", "HTTP status code", "number"),
    item("status", "status", "property", "HTTP status text", "string"),
    item(
      "responseTime",
      "responseTime",
      "property",
      "Response time in ms",
      "number",
    ),
    item("headers", "headers", "property", "Response headers", "HeaderList"),
    item("cookies", "cookies", "property", "Response cookies", "CookieList"),
    item("size", "size()", "method", "Response size info", "() => object"),
    item(
      "to",
      "to",
      "property",
      "Postman-style assertions",
      "ResponseAssertion",
    ),
  ],
  "pm.request": [
    item("url", "url", "property", "Request URL", "string"),
    item("method", "method", "property", "Request method", "string"),
    item("headers", "headers", "property", "Request headers", "HeaderList"),
    item("body", "body", "property", "Request body", "any"),
    item("auth", "auth", "property", "Request auth", "any"),
    item(
      "addHeader",
      'addHeader({ key: "Header-Name", value: "value" })',
      "method",
      "Add request header",
      "(header) => void",
    ),
    item(
      "getHeaders",
      "getHeaders()",
      "method",
      "List request headers",
      "() => Header[]",
    ),
    item(
      "removeHeader",
      'removeHeader("Header-Name")',
      "method",
      "Remove request header",
      "(key) => void",
    ),
  ],
  "pm.request.headers": headerSuggestions("Request header"),
  "pm.response.headers": headerSuggestions("Response header"),
  "pm.response.to": [
    item(
      "have",
      "have",
      "property",
      "Response assertions",
      "ResponseHaveAssertion",
    ),
  ],
  "pm.response.to.have": [
    item(
      "status",
      "status(200)",
      "method",
      "Assert status code",
      "(code) => void",
    ),
    item(
      "body",
      'body("text")',
      "method",
      "Assert body text",
      "(text) => void",
    ),
    item(
      "header",
      'header("Header-Name")',
      "method",
      "Assert header exists",
      "(key) => void",
    ),
  ],
};
