import { describe, expect, test } from "bun:test";

import type { Collection, TabData } from "@/contexts/WorkspaceContext";
import { generateCurlCommand } from "@/utils/curlGenerator";

function request(overrides: Partial<TabData>): TabData {
  return {
    id: "tab",
    name: "Request",
    method: "POST",
    url: "https://api.example.com",
    headers: [],
    authType: "none",
    bodyType: "none",
    body: "",
    response: null,
    ...overrides,
  };
}

describe("generateCurlCommand extra cases", () => {
  test("adds bearer token header if inherited", () => {
    const col: Collection = {
      id: "c1",
      name: "Col",
      authType: "bearer",
      bearerToken: "my-token",
      items: [],
      variables: [],
    };

    const curl = generateCurlCommand({
      collections: [col],
      globalVariables: [],
      request: request({
        collectionId: "c1",
        authType: "inherit",
      }),
    });

    expect(curl).toContain("Authorization: Bearer my-token");
  });

  test("generates x-www-form-urlencoded body", () => {
    const curl = generateCurlCommand({
      collections: [],
      globalVariables: [],
      request: request({
        bodyType: "x-www-form-urlencoded",
        formData: [
          {
            id: "1",
            key: "username",
            value: "admin",
            type: "text",
            enabled: true,
          },
          {
            id: "2",
            key: "password",
            value: "pass",
            type: "text",
            enabled: true,
          },
          { id: "3", key: "", value: "ignored", type: "text", enabled: true },
          {
            id: "4",
            key: "disabled",
            value: "ignored",
            type: "text",
            enabled: false,
          },
        ],
      }),
    });

    expect(curl).toContain("--data-urlencode 'username=admin'");
    expect(curl).toContain("--data-urlencode 'password=pass'");
    expect(curl).not.toContain("disabled");
  });

  test("generates form-data body with text and files, skipping auto-generated content-type", () => {
    const curl = generateCurlCommand({
      collections: [],
      globalVariables: [],
      request: request({
        bodyType: "form-data",
        headers: [
          {
            key: "Content-Type",
            value: "multipart/form-data; boundary=---",
            enabled: true,
          },
          { key: "X-Custom", value: "CustomValue", enabled: true },
        ],
        formData: [
          {
            id: "5",
            key: "profile",
            value: "",
            type: "file",
            enabled: true,
            files: ["/path/to/image.png"],
          },
          { id: "6", key: "name", value: "Admin", type: "text", enabled: true },
        ],
      }),
    });

    // Content type for form-data is skipped because it's auto-generated by curl
    expect(curl).not.toContain("multipart/form-data");
    expect(curl).toContain("X-Custom: CustomValue");
    expect(curl).toContain("--form 'profile=@/path/to/image.png'");
    expect(curl).toContain("--form 'name=Admin'");
  });
});
